### ISSUE TITLE
dbconn.py 까치울역 rows drop 필요

### ISSUE THREAD

**Issue by usiohc** [TonysHub/subway#22]
까치울역 삭제 필요

![image](https://user-images.githubusercontent.com/89768234/235909829-f04164fa-d4e3-407c-8975-6bc528dbb18f.png)

![image](https://user-images.githubusercontent.com/89768234/235909637-d36be216-b798-4b8c-a5d1-6e6e987c7267.png)

**Comment by TonysHub** [comment]
ㅋㅋㅋ 2주에 두 명 타는 역도 있네요 ㅋㅋㅋㅋㅋ

저거 db에서 drop보다 plot 하면서 outlier 제거하는게 나아보입니다!
0이랑 너무 낮은 값들은 outlier로 둬도 될 것 같아요
